"use client";

import { useEffect, useState } from "react";
import { apiGet, assetUrl } from "@/lib/api";
import type { FooterSettings, Social } from "@/types";

export default function Footer() {
  const [settings, setSettings] = useState<FooterSettings>({});
  const [socials, setSocials] = useState<Social[]>([]);
  useEffect(() => { Promise.allSettled([apiGet<FooterSettings>("/api/footer-settings"), apiGet<Social[]>("/api/footer-socials")]).then(([a,b]) => { if (a.status === "fulfilled") setSettings(a.value || {}); if (b.status === "fulfilled") setSocials(b.value || []); }); }, []);
  const icon = (platform?: string) => { const p = String(platform || "").toLowerCase(); if (p.includes("linkedin")) return "in"; if (p.includes("facebook")) return "f"; if (p.includes("youtube")) return "▶"; if (p.includes("instagram")) return "◎"; return "𝕏"; };
  return <footer className="text-hero-foreground" style={{ background: "#051895", padding: "3.5rem 1.5rem" }}><div className="mx-auto max-w-screen-2xl"><div className="footer-inner"><div style={{ maxWidth: "32rem" }}><div className="flex items-center"><img src={assetUrl(settings.logo_image) || "/images/kds-logo-full.png"} alt={settings.logo_alt_text || "KDS ERP Crew"} style={{ height: "3.75rem", objectFit: "contain" }} /></div><h3 className="text-hero-foreground" style={{ marginTop: "1.5rem", fontSize: "1rem", fontWeight: 700 }}>{settings.about_heading || "About Key Dynamics Solutions (KDS)"}</h3><p className="text-hero-muted" style={{ marginTop: ".5rem", fontSize: ".875rem", lineHeight: 1.625 }}>{settings.about_text || "KDS ERP Crew is an AI-powered enterprise automation platform developed and owned by Key Dynamics Solutions."}</p></div><div className="footer-right"><p className="text-hero-foreground" style={{ fontSize: ".875rem", fontWeight: 600 }}>{settings.info_heading || "Want to know more about KDS?"}</p><p className="text-hero-muted" style={{ maxWidth: "20rem", fontSize: ".875rem", lineHeight: 1.625 }}>{settings.info_text || "Discover our solutions, services, and success stories by visiting the KDS website."}</p><a href={settings.info_link_url || "https://keydynamicssolutions.com/"} target="_blank" rel="noopener noreferrer" className="footer-kds-link" style={{ fontSize: ".875rem", fontWeight: 600, color: "#fff", textDecoration: "underline" }}>{settings.info_link_text || "Visit KDS Website →"}</a><div className="footer-divider" /><h3 className="text-hero-foreground" style={{ fontSize: "1rem", fontWeight: 700 }}>{settings.connect_heading || "Connect With KDS"}</h3><p className="text-hero-muted" style={{ maxWidth: "20rem", fontSize: ".875rem", lineHeight: 1.625 }}>{settings.connect_text || "Stay connected for the latest updates and AI innovations."}</p><div style={{ display: "flex", alignItems: "center", gap: "1rem" }}>{socials.map((s, i) => <a key={i} href={s.url || "#"} target="_blank" rel="noopener noreferrer" aria-label={s.platform || "social"} className="footer-social-btn">{icon(s.icon || s.platform)}</a>)}</div></div></div><div className="footer-copyright"><p className="text-hero-muted" style={{ fontSize: ".75rem" }}>{settings.copyright_text || "© 2026 Key Dynamics Solutions Pvt. Ltd. All Rights Reserved. KDS ERP Crew™ is a product of Key Dynamics Solutions."}</p></div></div></footer>;
}
